table dProdutos
	lineageTag: 33edcbed-17d2-40ce-923a-6680327262af

	column 'Id Produto'
		dataType: int64
		formatString: 0
		lineageTag: 9ded8082-a715-45b9-b845-99651cd4c429
		summarizeBy: none
		sourceColumn: Id Produto

		annotation SummarizationSetBy = Automatic

	column Produto
		dataType: string
		lineageTag: cc1410ed-919d-4dca-a18f-985139f273ff
		summarizeBy: none
		sourceColumn: Produto

		annotation SummarizationSetBy = Automatic

	column Categoria
		dataType: string
		lineageTag: 4bede663-4521-4d5a-8597-38a79d37a1ea
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column Subcategoria
		dataType: string
		lineageTag: a59531aa-d679-40a4-8960-cd995411997b
		summarizeBy: none
		sourceColumn: Subcategoria

		annotation SummarizationSetBy = Automatic

	column Marca
		dataType: string
		lineageTag: 5e08e688-655e-4088-b1a2-11ef8baaa064
		summarizeBy: none
		sourceColumn: Marca

		annotation SummarizationSetBy = Automatic

	partition dProdutos = m
		mode: import
		queryGroup: Dimensao
		source =
				let
				    Source = Excel.Workbook(File.Contents(dCaminho), null, true),
				    Produtos_Table = Source{[Item="Produtos",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Produtos_Table,{{"Id Produto", Int64.Type}, {"Produto", type text}, {"Categoria", type text}, {"Subcategoria", type text}, {"Marca", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

